GET http://localhost:8000/api/posts HTTP/1.1


###




POST http://localhost:8000/api/posts HTTP/1.1

Content-Type: application/json

{
    "status": "My third status",
    "position": "My third position"
}